inherit_from: .rubocop_todo.yml

require: rubocop-rails

AllCops:
  TargetRubyVersion: 2.7.1
  Exclude:
    - 'bin/**/*'
    - db/schema.rb
    - db/seeds.rb
    - db/migrate/*
    - 'vendor/**/*'
    - 'config/**/*'
Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: true
  Max: 20
  Exclude:
    - 'test/**/*'

Metrics/BlockLength:
  CountComments: false
  Max: 25
  Exclude:
    - 'Rakefile'
    - 'config/routes.rb'
    - 'config/routes/*'
    - 'config/environments/*'
    - '**/*.rake'
    - 'spec/**/*'
  ExcludedMethods: ['class_methods']

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  CountComments: false
  Max: 15
  Exclude:
    - 'test/**/*'

Metrics/ParameterLists:
  Exclude:
    - 'test/**/*'

Naming/PredicateName:
  Enabled: true
  NamePrefix:
    - is_
    - not_
    - does_
    - can_
  ForbiddenPrefixes:
    - is_
    - not_
    - does_
    - can_

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max: 100
  Exclude:
    - 'config/routes.rb'
    - 'config/routes/*'
    - 'config/environments/*'
    - 'config/environments/*'
    - 'db/seeds.rb'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/DotPosition:
  EnforcedStyle: leading

Rails/Delegate:
  EnforceForPrefixed: false

Rails/RakeEnvironment:
  Enabled: false

Style/CollectionMethods:
  Enabled: true
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Style/EachWithObject:
  Enabled: false

Style/GlobalVars:
  AllowedVariables: [$fog_storage, $redis]

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%r': '{}'
    '%w': '()'
    '%W': '()'
    '%i': '()'
    '%I': '()'

Style/RaiseArgs:
  EnforcedStyle: compact

Style/SignalException:
  EnforcedStyle: only_raise

Style/SingleLineMethods:
  AllowIfMethodIsEmpty: false

# Style/StringLiterals:
#   EnforcedStyle: double_quotes

# Style/StringLiteralsInInterpolation:
#   EnforcedStyle: double_quotes

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/WordArray:
  EnforcedStyle: percent

Style/NumericLiterals:
  Enabled: true
  MinDigits: 5
  Strict: false
  Exclude:
    - 'test/**/*'

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Style/AccessorGrouping:
  Enabled: true

Style/ArrayCoercion:
  Enabled: true

Style/BisectedAttrAccessor:
  Enabled: true

Style/CaseLikeIf:
  Enabled: true

Style/HashAsLastArrayItem:
  Enabled: true

Style/HashLikeCase:
  Enabled: true

Style/RedundantAssignment:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantFileExtensionInRequire:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true
